// Generated by gencpp from file auto_driving/Detection.msg
// DO NOT EDIT!


#ifndef AUTO_DRIVING_MESSAGE_DETECTION_H
#define AUTO_DRIVING_MESSAGE_DETECTION_H

#include <ros/service_traits.h>


#include <auto_driving/DetectionRequest.h>
#include <auto_driving/DetectionResponse.h>


namespace auto_driving
{

struct Detection
{

typedef DetectionRequest Request;
typedef DetectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detection
} // namespace auto_driving


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_driving::Detection > {
  static const char* value()
  {
    return "0ed8b4b501f348884acc82d51e666664";
  }

  static const char* value(const ::auto_driving::Detection&) { return value(); }
};

template<>
struct DataType< ::auto_driving::Detection > {
  static const char* value()
  {
    return "auto_driving/Detection";
  }

  static const char* value(const ::auto_driving::Detection&) { return value(); }
};


// service_traits::MD5Sum< ::auto_driving::DetectionRequest> should match 
// service_traits::MD5Sum< ::auto_driving::Detection > 
template<>
struct MD5Sum< ::auto_driving::DetectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_driving::Detection >::value();
  }
  static const char* value(const ::auto_driving::DetectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_driving::DetectionRequest> should match 
// service_traits::DataType< ::auto_driving::Detection > 
template<>
struct DataType< ::auto_driving::DetectionRequest>
{
  static const char* value()
  {
    return DataType< ::auto_driving::Detection >::value();
  }
  static const char* value(const ::auto_driving::DetectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_driving::DetectionResponse> should match 
// service_traits::MD5Sum< ::auto_driving::Detection > 
template<>
struct MD5Sum< ::auto_driving::DetectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_driving::Detection >::value();
  }
  static const char* value(const ::auto_driving::DetectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_driving::DetectionResponse> should match 
// service_traits::DataType< ::auto_driving::Detection > 
template<>
struct DataType< ::auto_driving::DetectionResponse>
{
  static const char* value()
  {
    return DataType< ::auto_driving::Detection >::value();
  }
  static const char* value(const ::auto_driving::DetectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_DRIVING_MESSAGE_DETECTION_H
