// Generated by gencpp from file auto_driving/DetectionResponse.msg
// DO NOT EDIT!


#ifndef AUTO_DRIVING_MESSAGE_DETECTIONRESPONSE_H
#define AUTO_DRIVING_MESSAGE_DETECTIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_driving
{
template <class ContainerAllocator>
struct DetectionResponse_
{
  typedef DetectionResponse_<ContainerAllocator> Type;

  DetectionResponse_()
    : max(0)  {
    }
  DetectionResponse_(const ContainerAllocator& _alloc)
    : max(0)  {
  (void)_alloc;
    }



   typedef int64_t _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::auto_driving::DetectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_driving::DetectionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionResponse_

typedef ::auto_driving::DetectionResponse_<std::allocator<void> > DetectionResponse;

typedef boost::shared_ptr< ::auto_driving::DetectionResponse > DetectionResponsePtr;
typedef boost::shared_ptr< ::auto_driving::DetectionResponse const> DetectionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_driving::DetectionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_driving::DetectionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_driving

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'auto_driving': ['/home/alexandru/Documents/GitRepos/AuthonomousDriving/AuthonomousDriving/src/auto_driving/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_driving::DetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_driving::DetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_driving::DetectionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_driving::DetectionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_driving::DetectionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_driving::DetectionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_driving::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1978653de1814b9f74fe866ab7d0d762";
  }

  static const char* value(const ::auto_driving::DetectionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1978653de1814b9fULL;
  static const uint64_t static_value2 = 0x74fe866ab7d0d762ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_driving::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_driving/DetectionResponse";
  }

  static const char* value(const ::auto_driving::DetectionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_driving::DetectionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 max\n\
\n\
";
  }

  static const char* value(const ::auto_driving::DetectionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_driving::DetectionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_driving::DetectionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_driving::DetectionResponse_<ContainerAllocator>& v)
  {
    s << indent << "max: ";
    Printer<int64_t>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_DRIVING_MESSAGE_DETECTIONRESPONSE_H
